"""baseline

Revision ID: 0396550bb073
Revises: 
Create Date: 2026-02-05 23:21:27.992011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0396550bb073'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('capa', 'type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('CORRECTIVE', 'PREVENTIVE', name='capatype'),
               nullable=False,
               existing_server_default=sa.text("'CORRECTIVE'::character varying"))
    op.alter_column('capa', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='capastatus'),
               nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.drop_column('capa', 'is_completed')
    op.alter_column('incident', 'category',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('ELECTRICAL', 'MECHANICAL', 'CIVIL', 'FIRE', 'CHEMICAL', 'GENERAL', 'UNSAFE_ACT', 'UNSAFE_CONDITION', name='incidentcategory'),
               existing_nullable=False,
               existing_server_default=sa.text("'GENERAL'::character varying"))
    op.drop_column('incident', 'photos')
    op.add_column('investigation', sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='investigationstatus'), nullable=False))
    op.add_column('machine', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machine', 'image_url')
    op.drop_column('investigation', 'status')
    op.add_column('incident', sa.Column('photos', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('incident', 'category',
               existing_type=sa.Enum('ELECTRICAL', 'MECHANICAL', 'CIVIL', 'FIRE', 'CHEMICAL', 'GENERAL', 'UNSAFE_ACT', 'UNSAFE_CONDITION', name='incidentcategory'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'GENERAL'::character varying"))
    op.add_column('capa', sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('capa', 'status',
               existing_type=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='capastatus'),
               type_=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.alter_column('capa', 'type',
               existing_type=sa.Enum('CORRECTIVE', 'PREVENTIVE', name='capatype'),
               type_=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'CORRECTIVE'::character varying"))
    # ### end Alembic commands ###
