"""add machine module tables

Revision ID: 244832c804b2
Revises: 8f4ee06638a1
Create Date: 2026-01-31 17:35:09.441426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # <-- ADD THIS LINE


# revision identifiers, used by Alembic.
revision: str = '244832c804b2'
down_revision: Union[str, Sequence[str], None] = '8f4ee06638a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machinetype',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machinetype_name'), 'machinetype', ['name'], unique=True)
    op.create_table('shop',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_code'), 'shop', ['code'], unique=True)
    op.create_index(op.f('ix_shop_name'), 'shop', ['name'], unique=True)
    op.create_table('machine',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('criticality', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_maintenance_date', sa.Date(), nullable=True),
    sa.Column('install_year', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('type_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['machinetype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_asset_id'), 'machine', ['asset_id'], unique=True)
    op.create_table('maintenanceplan',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('frequency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('machine_type_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['machine_type_id'], ['machinetype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenancetask',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('requires_ppe', sa.Boolean(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['maintenanceplan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenancetask')
    op.drop_table('maintenanceplan')
    op.drop_index(op.f('ix_machine_asset_id'), table_name='machine')
    op.drop_table('machine')
    op.drop_index(op.f('ix_shop_name'), table_name='shop')
    op.drop_index(op.f('ix_shop_code'), table_name='shop')
    op.drop_table('shop')
    op.drop_index(op.f('ix_machinetype_name'), table_name='machinetype')
    op.drop_table('machinetype')
    # ### end Alembic commands ###
