"""Add time-based and extension fields to permit table

Revision ID: 8f4ee06638a1
Revises: b157bb245130
Create Date: 2025-10-31 00:42:33.294637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8f4ee06638a1'
down_revision: Union[str, Sequence[str], None] = 'b157bb245130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permit', sa.Column('actual_start_time', sa.DateTime(), nullable=True))
    op.add_column('permit', sa.Column('actual_end_time', sa.DateTime(), nullable=True))
    op.add_column('permit', sa.Column('extension_requested', sa.Boolean(), nullable=True))
    op.add_column('permit', sa.Column('extension_reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('permit', sa.Column('requested_new_end_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_permit_extension_requested'), 'permit', ['extension_requested'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permit_extension_requested'), table_name='permit')
    op.drop_column('permit', 'requested_new_end_time')
    op.drop_column('permit', 'extension_reason')
    op.drop_column('permit', 'extension_requested')
    op.drop_column('permit', 'actual_end_time')
    op.drop_column('permit', 'actual_start_time')
    # ### end Alembic commands ###
