"""Create permit, permit_ppe, and permit_attendee tables

Revision ID: b157bb245130
Revises: 
Create Date: 2025-10-30 23:08:21.457057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b157bb245130'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permit',
    sa.Column('permit_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('permit_no', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('person_responsible', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('work_location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('work_description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('finish_date', sa.Date(), nullable=True),
    sa.Column('finish_time', sa.Time(), nullable=True),
    sa.Column('fall_system_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fall_does_not_arrest', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('certified_crane_near_ladder', sa.Boolean(), nullable=True),
    sa.Column('on_crane_describe', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('other_describe', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hazard_assessed', sa.Boolean(), nullable=True),
    sa.Column('work_can_proceed', sa.Boolean(), nullable=True),
    sa.Column('method_access_fixed_ladder', sa.Boolean(), nullable=True),
    sa.Column('method_access_elevated_platform', sa.Boolean(), nullable=True),
    sa.Column('method_access_scissor_lift', sa.Boolean(), nullable=True),
    sa.Column('method_access_boom_lifter', sa.Boolean(), nullable=True),
    sa.Column('method_access_catwalk', sa.Boolean(), nullable=True),
    sa.Column('fixed_ladder_other_person_at_foot', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fixed_ladder_adjustable_lanyard', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('electrical_isolation_obtained', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('isolation_from', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('isolation_to', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('other_block_required', sa.Boolean(), nullable=True),
    sa.Column('other_block_describe', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('authorizer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('authorizer_signature_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('permittee_id', sa.Uuid(), nullable=False),
    sa.Column('authorizer_id', sa.Uuid(), nullable=True),
    sa.Column('authorized_at', sa.DateTime(), nullable=True),
    sa.Column('approver_id', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approver_remarks', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['authorizer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['permittee_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permit_approver_id'), 'permit', ['approver_id'], unique=False)
    op.create_index(op.f('ix_permit_authorizer_id'), 'permit', ['authorizer_id'], unique=False)
    op.create_index(op.f('ix_permit_permit_no'), 'permit', ['permit_no'], unique=False)
    op.create_index(op.f('ix_permit_permit_type'), 'permit', ['permit_type'], unique=False)
    op.create_index(op.f('ix_permit_permittee_id'), 'permit', ['permittee_id'], unique=False)
    op.create_index(op.f('ix_permit_status'), 'permit', ['status'], unique=False)
    op.create_table('permitattendee',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('permit_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['permit_id'], ['permit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permitattendee_permit_id'), 'permitattendee', ['permit_id'], unique=False)
    op.create_table('permitppe',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('permit_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('issued_on', sa.Date(), nullable=True),
    sa.Column('checked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['permit_id'], ['permit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permitppe_permit_id'), 'permitppe', ['permit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permitppe_permit_id'), table_name='permitppe')
    op.drop_table('permitppe')
    op.drop_index(op.f('ix_permitattendee_permit_id'), table_name='permitattendee')
    op.drop_table('permitattendee')
    op.drop_index(op.f('ix_permit_status'), table_name='permit')
    op.drop_index(op.f('ix_permit_permittee_id'), table_name='permit')
    op.drop_index(op.f('ix_permit_permit_type'), table_name='permit')
    op.drop_index(op.f('ix_permit_permit_no'), table_name='permit')
    op.drop_index(op.f('ix_permit_authorizer_id'), table_name='permit')
    op.drop_index(op.f('ix_permit_approver_id'), table_name='permit')
    op.drop_table('permit')
    # ### end Alembic commands ###
