"""Link Permit to Machine and MaintenancePlan

Revision ID: f4549aaa9f76
Revises: 244832c804b2
Create Date: 2026-01-31 20:22:38.155559

"""
from typing import Sequence, Union
from sqlalchemy.sql import text

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4549aaa9f76'
down_revision: Union[str, Sequence[str], None] = '244832c804b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permit', sa.Column('machine_id', sa.Uuid(), nullable=True))
    op.add_column('permit', sa.Column('maintenance_plan_id', sa.Uuid(), nullable=True))
    op.add_column('permit', sa.Column('is_critical', sa.Boolean(), nullable=False, server_default=text('false')))
    op.create_index(op.f('ix_permit_machine_id'), 'permit', ['machine_id'], unique=False)
    op.create_foreign_key(None, 'permit', 'machine', ['machine_id'], ['id'])
    op.create_foreign_key(None, 'permit', 'maintenanceplan', ['maintenance_plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'permit', type_='foreignkey')
    op.drop_constraint(None, 'permit', type_='foreignkey')
    op.drop_index(op.f('ix_permit_machine_id'), table_name='permit')
    op.drop_column('permit', 'is_critical')
    op.drop_column('permit', 'maintenance_plan_id')
    op.drop_column('permit', 'machine_id')
    # ### end Alembic commands ###
